### ISSUE TITLE
No Echo not working

### ISSUE THREAD

**Issue by EwiththeBowtie** [EMnify/sparkleformation-docker#1]
With a parameter set to no echo, like so:
```
database_password do
  type 'String'
  no_echo true
end
```

I'm getting this error.
```
[Sfn]: Database Password []: ERROR: NoMethodError: undefined method `noecho' for #<IO:<STDIN>>
```

**Comment by StephenKing** [comment]
Thanks for using our docker container. Please be warned that we're currently fading out SparkleFormation in our infrastructure and the containers might be deleted in the soon future.

Similar to other issues of this type (veelenga/jira_report#5 or kentaroi/sshkit-sudo#4), the solution is to include the `io/console` gem by add the following line to your SFN templates:

    require 'io/console'

**Comment by EwiththeBowtie** [comment]
Thank you!  I appreciate it.  I'll make sure my team has their Dockerfile setup instead of running off of your DockerHub repo.
